language: shell
services:
  - docker
sudo: required
branches:
  only:
  - master
before_install:
  - chmod +x *.sh
install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config user.name "blademainer"
- git config user.email "blademainer@gmail.com"
- ./mkdocs-publish.sh
